dbtlearn:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/tiago/Documents/BigQuery/dbt-user-creds.json
      location: US
      method: service-account
      priority: interactive
      project: intricate-shard-445109-t4
      threads: 1
      type: bigquery
  target: dev
